services:
  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak_user
      POSTGRES_PASSWORD: KcDb#2026!Dev
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U keycloak" ]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.6
    command: start --import-realm --hostname-strict=false
    restart: always
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://pow-it-up.postgres.database.azure.com:5432/keycloak?sslmode=require
      KC_DB_USERNAME: keycloak_user
      KC_DB_PASSWORD: KcDb#2026!Dev

      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

      KC_HOSTNAME: keycloaktest-hqd7chf7h8bjevha.centralus-01.azurewebsites.net
      KC_HOSTNAME_STRICT: "false"
      KC_HTTP_ENABLED: "true"
      KC_PROXY: edge

      WEBSITES_PORT: 8080
    ports:
      - "80:8080"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
